nameOverride: ""
fullnameOverride: ""

# --- Настройки Backend (Remnawave) ---
backend:
  replicaCount: 1
  image:
    repository: remnawave/backend
    tag: "2.7.4"
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 250m
      memory: 512Mi

# --- Конфигурация приложения (ConfigMap) ---
config:
  appPort: 3000
  metricsPort: 3001
  apiInstances: 1
  panelDomain: panel.domain.com
  frontEndDomain: "*"
  subPublicDomain: panel.domain.com/api/sub
  swaggerPath: /docs
  scalarPath: /scalar
  isDocsEnabled: "false"
  telegramNotificationsEnabled: "false"
  webhookEnabled: "false"
  webhookUrl: ""
  bandwidthUsageNotificationsEnabled: "false"
  bandwidthUsageNotificationsThreshold: "[60, 80]"
  notConnectedUsersNotificationsEnabled: "false"
  notConnectedUsersNotificationsAfterHours: "[6, 24, 48]"

secrets:
  # 1. JWT (Авторизация и токены API)
  jwt:
    existingSecret: "" # Если указано, ключи берутся оттуда (ожидаются: JWT_AUTH_SECRET, JWT_API_TOKENS_SECRET)
    authSecret: "change_me"
    apiTokensSecret: "change_me"

  # 2. Telegram (Уведомления)
  telegram:
    existingSecret: "" # Ожидаются ключи: TELEGRAM_BOT_TOKEN, TELEGRAM_NOTIFY_...
    botToken: "change_me"
    notifyUsers: "change_me"
    notifyNodes: "change_me"
    notifyCrm: "change_me"
    notifyService: "change_me"
    notifyTblocker: "change_me"

  # 3. Метрики и Webhook
  metrics:
    existingSecret: "" # Ожидаются: METRICS_USER, METRICS_PASS, WEBHOOK_SECRET_HEADER
    metricsUser: "admin"
    metricsPass: "admin"
    webhookSecretHeader: "vsmu67Kmg6R8FjIOF1WUY8LWBHie4scdEqrfsKmyf4IAf8dY3nFS0wwYHkhh6ZvQ"

  # 4. Внешняя база данных (Используется ТОЛЬКО если cnpg.enabled: false)
  database:
    existingSecret: "" # Ожидается ключ: DATABASE_URL
    url: "postgresql://postgres:postgres@external-host:5432/postgres"

# --- Настройки Valkey (Кэш) ---
valkey:
  image:
    repository: valkey/valkey
    tag: 9-alpine
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# --- Настройки базы данных (CloudNativePG) ---
cnpg:
  enabled: true # Флаг, если БД управляется извне, можно выключить
  instances: 1  # Для k3s 1 инстанс ОК, для HA ставим 3
  storage:
    size: 10Gi
    storageClass: local-path # дефолт k3s
  backup:
    enabled: false
    bucketName: "remnawave-backups"
    endpointURL: "https://s3.amazonaws.com"
    existingSecret: "cnpg-s3-credentials" # Secret with ACCESS_KEY_ID and ACCESS_SECRET_KEY
    serverName: "remnawave-db"
    retentionPolicy: "30d"

# --- Настройки Ingress ---
ingress:
  enabled: false
  className: "traefik" # дефолт k3s
  annotations: {}
    # kubernetes.io/ingress.class: traefik
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: panel.domain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: remnawave-tls-secret
  #    hosts:
  #      - panel.domain.com

# --- Настройки Мониторинга (Prometheus Operator) ---
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  
  # Лейблы, по которым Prometheus Operator ищет ServiceMonitor'ы (часто это release: prometheus или kube-prometheus-stack)
  additionalLabels:
    release: prometheus
  
  # Настройка авторизации
  basicAuth:
    enabled: true # Установи true, если эндпоинт /metrics защищен (METRICS_USER и METRICS_PASS)