apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "remnaware.fullname" . }}
  labels:
    {{- include "remnaware.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "remnaware.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "remnaware.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http-app
              containerPort: {{ .Values.config.appPort }}
            - name: http-metrics
              containerPort: {{ .Values.config.metricsPort }}
          
          # Загружаем все переменные из ConfigMap и Secret
          envFrom:
            # 1. Загружаем нечувствительные конфиги
            - configMapRef:
                name: {{ include "remnaware.fullname" . }}-config
            # 2. Загружаем JWT
            - secretRef:
                name: {{ include "remnaware.secretName.jwt" . }}
            # 3. Загружаем Telegram
            - secretRef:
                name: {{ include "remnaware.secretName.telegram" . }}
            # 4. Загружаем Метрики
            - secretRef:
                name: {{ include "remnaware.secretName.metrics" . }}
          
          # Подключение к БД (CNPG или внешняя)
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  {{- if .Values.cnpg.enabled }}
                  # Если CNPG включен, берем секрет, сгенерированный оператором
                  name: {{ include "remnaware.fullname" . }}-db-app
                  key: uri
                  {{- else }}
                  # Если CNPG выключен, берем наш секрет (или внешний)
                  name: {{ include "remnaware.secretName.database" . }}
                  key: DATABASE_URL
                  {{- end }}
          
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          
          livenessProbe:
            httpGet:
              path: /health
              port: http-metrics
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /health
              port: http-metrics
            initialDelaySeconds: 5
            periodSeconds: 10