{{- if and .Values.cnpg.enabled .Values.cnpg.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "remnaware.fullname" . }}-daily-backup
  labels:
    {{- include "remnaware.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cnpg.backup.schedule | quote }}
  {{- if .Values.cnpg.backup.backupOwner }}
  backupOwner: {{ .Values.cnpg.backup.backupOwner | quote }}
  {{- else }}
  backupOwner: primary
  {{- end }}
  cluster:
    name: {{ include "remnaware.fullname" . }}-db
{{- end }}