{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "remnaware.fullname" . }}-db
  labels:
    {{- include "remnaware.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.cnpg.instances }}
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  
  primaryUpdateStrategy: unsupervised

  storage:
    size: {{ .Values.cnpg.storage.size }}
    storageClass: {{ .Values.cnpg.storage.storageClass }}
  {{- if .Values.cnpg.backup.enabled }}
  backup:
    barmanObjectStore:
      destinationPath: "s3://{{ .Values.cnpg.backup.bucketName }}/"
      endpointURL: {{ .Values.cnpg.backup.endpointURL | quote }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.cnpg.backup.existingSecret }}
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: {{ .Values.cnpg.backup.existingSecret }}
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      serverName: {{ .Values.cnpg.backup.serverName | quote }}
    retentionPolicy: {{ .Values.cnpg.backup.retentionPolicy | quote }}
{{- end }}

  bootstrap:
    initdb:
      database: remnawave
      owner: remnawave
{{- end }}
