apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "remnaware.fullname" . }}-config
  labels:
    {{- include "remnaware.labels" . | nindent 4 }}
data:
  APP_PORT: {{ .Values.config.appPort | quote }}
  METRICS_PORT: {{ .Values.config.metricsPort | quote }}
  API_INSTANCES: {{ .Values.config.apiInstances | quote }}
  PANEL_DOMAIN: {{ .Values.config.panelDomain | quote }}
  FRONT_END_DOMAIN: {{ .Values.config.frontEndDomain | quote }}
  SUB_PUBLIC_DOMAIN: {{ .Values.config.subPublicDomain | quote }}
  SWAGGER_PATH: {{ .Values.config.swaggerPath | quote }}
  SCALAR_PATH: {{ .Values.config.scalarPath | quote }}
  IS_DOCS_ENABLED: {{ .Values.config.isDocsEnabled | quote }}
  IS_TELEGRAM_NOTIFICATIONS_ENABLED: {{ .Values.config.telegramNotificationsEnabled | quote }}
  WEBHOOK_ENABLED: {{ .Values.config.webhookEnabled | quote }}
  WEBHOOK_URL: {{ .Values.config.webhookUrl | quote }}
  BANDWIDTH_USAGE_NOTIFICATIONS_ENABLED: {{ .Values.config.bandwidthUsageNotificationsEnabled | quote }}
  BANDWIDTH_USAGE_NOTIFICATIONS_THRESHOLD: {{ .Values.config.bandwidthUsageNotificationsThreshold | quote }}
  NOT_CONNECTED_USERS_NOTIFICATIONS_ENABLED: {{ .Values.config.notConnectedUsersNotificationsEnabled | quote }}
  NOT_CONNECTED_USERS_NOTIFICATIONS_AFTER_HOURS: {{ .Values.config.notConnectedUsersNotificationsAfterHours | quote }}
  # Настройки для Valkey (TCP вместо Socket)
  REDIS_HOST: {{ include "remnaware.fullname" . }}-valkey
  REDIS_PORT: "6379"