{{- if not .Values.secrets.jwt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remnaware.fullname" . }}-jwt
  labels:
    {{- include "remnaware.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_AUTH_SECRET: {{ .Values.secrets.jwt.authSecret | quote }}
  JWT_API_TOKENS_SECRET: {{ .Values.secrets.jwt.apiTokensSecret | quote }}
{{- end }}