{{- if not .Values.secrets.metrics.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remnaware.fullname" . }}-metrics
  labels:
    {{- include "remnaware.labels" . | nindent 4 }}
type: Opaque
stringData:
  METRICS_USER: {{ .Values.secrets.metrics.metricsUser | quote }}
  METRICS_PASS: {{ .Values.secrets.metrics.metricsPass | quote }}
  WEBHOOK_SECRET_HEADER: {{ .Values.secrets.metrics.webhookSecretHeader | quote }}
{{- end }}