{{- if not .Values.secrets.telegram.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remnaware.fullname" . }}-telegram
  labels:
    {{- include "remnaware.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegram.botToken | quote }}
  TELEGRAM_NOTIFY_USERS: {{ .Values.secrets.telegram.notifyUsers | quote }}
  TELEGRAM_NOTIFY_NODES: {{ .Values.secrets.telegram.notifyNodes | quote }}
  TELEGRAM_NOTIFY_CRM: {{ .Values.secrets.telegram.notifyCrm | quote }}
  TELEGRAM_NOTIFY_SERVICE: {{ .Values.secrets.telegram.notifyService | quote }}
  TELEGRAM_NOTIFY_TBLOCKER: {{ .Values.secrets.telegram.notifyTblocker | quote }}
{{- end }}