{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remnaware.fullname" . }}-secret
  labels:
    {{- include "remnaware.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_AUTH_SECRET: {{ .Values.secret.jwtAuthSecret | quote }}
  JWT_API_TOKENS_SECRET: {{ .Values.secret.jwtApiTokensSecret | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secret.telegramBotToken | quote }}
  TELEGRAM_NOTIFY_USERS: {{ .Values.secret.telegramNotifyUsers | quote }}
  TELEGRAM_NOTIFY_NODES: {{ .Values.secret.telegramNotifyNodes | quote }}
  TELEGRAM_NOTIFY_CRM: {{ .Values.secret.telegramNotifyCrm | quote }}
  TELEGRAM_NOTIFY_SERVICE: {{ .Values.secret.telegramNotifyService | quote }}
  TELEGRAM_NOTIFY_TBLOCKER: {{ .Values.secret.telegramNotifyTblocker | quote }}
  METRICS_USER: {{ .Values.secret.metricsUser | quote }}
  METRICS_PASS: {{ .Values.secret.metricsPass | quote }}
  WEBHOOK_SECRET_HEADER: {{ .Values.secret.webhookSecretHeader | quote }}
{{- end }}