apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remnaware.fullname" . }}-secret
  labels:
    {{- include "remnaware.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_AUTH_SECRET: {{ .Values.secret.jwtAuthSecret }}
  JWT_API_TOKENS_SECRET: {{ .Values.secret.jwtApiTokensSecret }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secret.telegramBotToken }}
  TELEGRAM_NOTIFY_USERS: {{ .Values.secret.telegramNotifyUsers }}
  TELEGRAM_NOTIFY_NODES: {{ .Values.secret.telegramNotifyNodes }}
  TELEGRAM_NOTIFY_CRM: {{ .Values.secret.telegramNotifyCrm }}
  TELEGRAM_NOTIFY_SERVICE: {{ .Values.secret.telegramNotifyService }}
  TELEGRAM_NOTIFY_TBLOCKER: {{ .Values.secret.telegramNotifyTblocker }}
  METRICS_USER: {{ .Values.secret.metricsUser }}
  METRICS_PASS: {{ .Values.secret.metricsPass }}
  WEBHOOK_SECRET_HEADER: {{ .Values.secret.webhookSecretHeader }}