{{- if and (not .Values.cnpg.enabled) (not .Values.secrets.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remnaware.fullname" . }}-external-db
  labels:
    {{- include "remnaware.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.database.url | quote }}
{{- end }}